---
- name: synchronize module demo
  hosts: all 
  become: true
  vars:
    source: '/work/copy-files-to-remote'
    destination:  '/example-backup' 
  tasks:
    - name: rsync installed
      ansible.builtin.package:
        name: rsync
        state: present
      become: true
    - name: data synchronization
      ansible.posix.synchronize:
        src:  '{{ source }}'
        dest: '{{ destination }}'
