---
- name: service restart demo
  hosts:  all
  become: true
  tasks:
    - name: restart sshd service
      ansible.builtin.service:
        name: sshd
        state:  restarted
        enabled:  true
