version: '3.8'
services:
  db:
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    restart: always
    container_name: mysql-database
volumes:
  db:
    driver: local

